# Generated by Django 4.2.7 on 2025-10-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('client', models.CharField(max_length=200, verbose_name='Клиент')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('ready', 'Готов'), ('archive', 'Архив')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content_type', models.CharField(choices=[('file', 'Файл'), ('html', 'HTML страница'), ('text', 'Текстовый блок'), ('link', 'Внешняя ссылка'), ('image', 'Изображение')], max_length=20, verbose_name='Тип контента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/files/', verbose_name='Файл')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML контент')),
                ('text_content', models.TextField(blank=True, verbose_name='Текстовый контент')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Контент проекта',
                'verbose_name_plural': 'Контент проектов',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
