# Generated by Django 5.2.7 on 2025-10-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_client_project_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контент проекта', 'verbose_name_plural': 'Контент проектов'},
        ),
        migrations.RemoveField(
            model_name='projectcontent',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectcontent',
            name='order',
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content_type',
            field=models.CharField(choices=[('html', 'HTML страница'), ('text', 'Текстовый блок'), ('link', 'Внешняя ссылка'), ('image', 'Изображение')], max_length=20, verbose_name='Тип контента'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='projects/files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
                'ordering': ['-created_at'],
            },
        ),
    ]
