# Generated by Django 5.2.7 on 2025-10-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content_type',
            field=models.CharField(choices=[('file', 'Файл'), ('html', 'HTML страница'), ('text', 'Текстовый блок'), ('link', 'Внешняя ссылка'), ('image', 'Изображение')], max_length=20, verbose_name='Тип контента'),
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
