# Generated by Django 5.2.7 on 2025-10-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Источник новостей',
                'verbose_name_plural': 'Источники новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на новость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newssource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
                'unique_together': {('url', 'source')},
            },
        ),
    ]
