# Generated by Django 4.2.7 on 2025-10-23 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('project_url', models.URLField(blank=True, verbose_name='Ссылка на проект')),
                ('work_description', models.TextField(verbose_name='Описание работы')),
                ('time_spent', models.DurationField(verbose_name='Потрачено времени')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Отчет о работе',
                'verbose_name_plural': 'Отчеты о работе',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
