# Generated by Django 5.2.7 on 2025-10-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcontent_file_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='Название проекта (если не выбран проект)'),
        ),
    ]
