# Generated by Django 5.2.7 on 2025-10-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(verbose_name='URL страницы')),
                ('page_title', models.CharField(blank=True, max_length=500, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('meta_robots', models.CharField(blank=True, max_length=200, verbose_name='Meta Robots')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('h1_tags', models.JSONField(default=list, verbose_name='H1 теги')),
                ('h2_tags', models.JSONField(default=list, verbose_name='H2 теги')),
                ('h3_tags', models.JSONField(default=list, verbose_name='H3 теги')),
                ('h4_tags', models.JSONField(default=list, verbose_name='H4 теги')),
                ('h5_tags', models.JSONField(default=list, verbose_name='H5 теги')),
                ('h6_tags', models.JSONField(default=list, verbose_name='H6 теги')),
                ('og_title', models.CharField(blank=True, max_length=500, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, verbose_name='OG Image')),
                ('og_type', models.CharField(blank=True, max_length=100, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, max_length=500, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, verbose_name='Twitter Image')),
                ('twitter_card', models.CharField(blank=True, max_length=100, verbose_name='Twitter Card')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Время ответа (сек)')),
                ('page_size', models.IntegerField(blank=True, null=True, verbose_name='Размер страницы (байт)')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP статус')),
                ('robots_txt', models.TextField(blank=True, verbose_name='robots.txt')),
                ('sitemap_xml', models.TextField(blank=True, verbose_name='sitemap.xml')),
                ('seo_issues', models.JSONField(default=list, verbose_name='SEO проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Базовый анализ',
                'verbose_name_plural': 'Базовые анализы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сайта')),
                ('name', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_competitor', models.BooleanField(default=False, verbose_name='Конкурент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Веб-сайт',
                'verbose_name_plural': 'Веб-сайты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meta', 'Мета-теги'), ('content', 'Контент'), ('technical', 'Техническая'), ('structure', 'Структура'), ('performance', 'Производительность')], max_length=20, verbose_name='Категория')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], max_length=20, verbose_name='Критичность')),
                ('title', models.CharField(max_length=200, verbose_name='Название проблемы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('recommendation', models.TextField(verbose_name='Рекомендация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tools.basicanalysis', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'SEO проблема',
                'verbose_name_plural': 'SEO проблемы',
                'ordering': ['-severity', 'category'],
            },
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='tools.website', verbose_name='Сайт'),
        ),
    ]
