# Generated by Django 5.2.7 on 2025-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(verbose_name='Домен')),
                ('analysis_type', models.CharField(choices=[('single', 'Анализ одного домена'), ('compare', 'Сравнение двух доменов'), ('competitors', 'СЯ конкурентов')], max_length=20, verbose_name='Тип анализа')),
                ('results', models.JSONField(default=list, verbose_name='Результаты')),
                ('total_found', models.IntegerField(default=0, verbose_name='Всего найдено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Анализ домена',
                'verbose_name_plural': 'Анализы доменов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Запрос')),
                ('search_type', models.CharField(choices=[('simple', 'Простой поиск'), ('extended', 'Расширенный поиск'), ('top', 'Топ запросов')], max_length=20, verbose_name='Тип поиска')),
                ('results', models.JSONField(default=list, verbose_name='Результаты')),
                ('total_found', models.IntegerField(default=0, verbose_name='Всего найдено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Поиск ключевых слов',
                'verbose_name_plural': 'Поиски ключевых слов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('normalize', 'Нормализатор слов'), ('deduplicate', 'Дедупликатор слов'), ('combine', 'Комбинатор слов'), ('compare', 'Компаратор слов'), ('analyze', 'Анализатор слов')], max_length=20, verbose_name='Тип инструмента')),
                ('input_data', models.TextField(verbose_name='Входные данные')),
                ('output_data', models.TextField(verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Инструмент ключевых слов',
                'verbose_name_plural': 'Инструменты ключевых слов',
                'ordering': ['-created_at'],
            },
        ),
    ]
