# Generated by Django 5.2.7 on 2025-10-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_domainanalysis_keywordsearch_keywordtool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainAnalysis',
        ),
        migrations.DeleteModel(
            name='KeywordSearch',
        ),
        migrations.DeleteModel(
            name='KeywordTool',
        ),
    ]
