# Generated by Django 5.2.7 on 2025-10-23 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_delete_domainanalysis_delete_keywordsearch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(verbose_name='URL страницы')),
                ('page_title', models.CharField(blank=True, max_length=500, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('word_count', models.IntegerField(default=0, verbose_name='Количество слов')),
                ('title_length', models.IntegerField(default=0, verbose_name='Длина title')),
                ('description_length', models.IntegerField(default=0, verbose_name='Длина description')),
                ('internal_links', models.IntegerField(default=0, verbose_name='Внутренние ссылки')),
                ('external_links', models.IntegerField(default=0, verbose_name='Внешние ссылки')),
                ('total_links', models.IntegerField(default=0, verbose_name='Всего ссылок')),
                ('keyword_analysis', models.JSONField(default=dict, verbose_name='Анализ ключевых слов')),
                ('page_size', models.IntegerField(default=0, verbose_name='Размер страницы')),
                ('response_time', models.FloatField(default=0.0, verbose_name='Время ответа')),
                ('status_code', models.IntegerField(default=0, verbose_name='HTTP статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.website', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Простые метрики',
                'verbose_name_plural': 'Простые метрики',
                'ordering': ['-created_at'],
            },
        ),
    ]
