# Generated by Django 5.2.7 on 2025-10-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_simplemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysis',
            name='description_length',
            field=models.IntegerField(default=0, verbose_name='Длина description'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='external_links',
            field=models.IntegerField(default=0, verbose_name='Внешние ссылки'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Извлеченный текст'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='internal_links',
            field=models.IntegerField(default=0, verbose_name='Внутренние ссылки'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='keyword_analysis',
            field=models.JSONField(default=dict, verbose_name='Анализ ключевых слов'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='title_length',
            field=models.IntegerField(default=0, verbose_name='Длина title'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='total_links',
            field=models.IntegerField(default=0, verbose_name='Всего ссылок'),
        ),
        migrations.AddField(
            model_name='basicanalysis',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='Количество слов'),
        ),
    ]
