# Generated by Django 5.2.7 on 2025-10-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_basicanalysis_description_length_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleMetrics',
        ),
    ]
