# Generated by Django 5.2.7 on 2025-10-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_delete_simplemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysis',
            name='detailed_links',
            field=models.JSONField(default=dict, verbose_name='Детальные ссылки'),
        ),
    ]
