# Generated by Django 5.2.7 on 2025-10-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_basicanalysis_detailed_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='Исходный текст')),
                ('translit_text', models.TextField(verbose_name='Транслит текст')),
                ('is_url', models.BooleanField(default=False, verbose_name='Это URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Результат транслита',
                'verbose_name_plural': 'Результаты транслита',
                'ordering': ['-created_at'],
            },
        ),
    ]
