# Generated by Django 5.2.7 on 2025-10-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#ffffff', help_text='HEX код цвета', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(default='bi-folder', help_text='Bootstrap Icons класс', max_length=50, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('resource_type', models.CharField(choices=[('article', 'Статья'), ('video', 'Видео'), ('tool', 'Инструмент'), ('script', 'Скрипт'), ('plugin', 'Плагин'), ('bookmark', 'Закладка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип ресурса')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/images/', verbose_name='Изображение')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Теги')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
