# Generated by Django 5.2.7 on 2025-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#808080', help_text='HEX код цвета', max_length=7, verbose_name='Цвет'),
        ),
    ]
